### PR TITLE
Default includeLibsJarsFromAar to true

### PR DESCRIPTION
**Pull request by Shusshu**
https://github.com/simpligility/android-maven-plugin/issues/583#issuecomment-74657334

Close https://github.com/simpligility/android-maven-plugin/issues/585

### CODE REVIEW

**Comment by Shusshu** [comment]
@william-ferguson-au double check ;)

**Comment by mosabua** [comment]
We need to make sure the build passes with it and should add a big fat warning in the log somehow.. personally I think we should leave it as false...

**Comment by william-ferguson-au** [comment]
Intellectually I agree with you Manfred.

But anyone that has to use support-v4 (which will be anyone attempting to
support prior versions of Android - ie everyone) or any of the others SDK
AARs that contain an internal lib will get failures that aren't going to be
immediately clear to them. It's going to appear like AMP is broken.

I think we have to default to include AAR libs.

But perhaps we add a warning IN  CAPS everytime we find an AAR containing
internal libs that briefly explains the problem.
ᐧ

**Comment by Shusshu** [comment]
We already have warnings to show we are added internal jars and where they come from...

**Comment by william-ferguson-au** [comment]
In that case just make it the default.


  [image: photo]
*William Ferguson*
Founder and CEO, XandarMob
 m:+61 425 716 870 | e:william.ferguson@xandar.com.au |
w:https://wylas-timing.com
http://lexathon.com <http://wylas-timing.com http://lexathon.com>
  ᐧ

On Wed, Feb 18, 2015 at 8:24 PM, Benoit Billington <notifications@github.com

**Comment by mosabua** [comment]
Fine by me... although really I would like to club the SDK team over the head and set it to false..

**Comment by mosabua** [comment]
Can you update the changelog and also change it to 4.2.0 there as next version. This is a compatiblity change worth upgrading minor version for on its own imho

**Comment by Shusshu** [comment]
Done

**Pull request merged**
