### PR TITLE
Use Travis Android support 

### PR DESCRIPTION
**Pull request by WonderCsabo**
This is a WIP. I did not squash the commits, so you can see exactly what steps I did while experimenting. 

This PR:
* uses native Travis Android
* Travis Docker infrastructure
* enables caching
* enables integration tests
* upgrades emulator to 22
* clean up .travis.yml
* changes Morseflash to use Espresso 

Unfortunately the Morseflash test fails sometimes, because the emulator is not unlocked despite it is instructed to. To debug this I print the build log and save the screenshots to a [repo]( https://github.com/WonderCsabo/hello/tree/75.1?files=1). Any help is appreciated to fix this last problem.

### CODE REVIEW

**Comment by mosabua** [comment]
Imho we should pull this in. And maybe improve the plugin to only kick off instrumentaiton

**Comment by mosabua** [comment]
Also this migrates from using robotium to espresso so we might have to update some docs. Do we still need a robotium example? Maybe not. Wdyt @simpligility/android-maven-plugins-core-committers

**Comment by WonderCsabo** [comment]
> Imho we should pull this in. 

Well, the build fails *lots of times* because of the problem i described. I asked about it on [adt-dev](https://groups.google.com/forum/#!topic/adt-dev/19XXQ1kC15g) for help.

> Also this migrates from using robotium to espresso

No, this migrates from plain instrumentation tests to Espresso.

> And maybe improve the plugin to only kick off instrumentaiton 

I do not understand.

**Comment by WonderCsabo** [comment]
Also, do not pull this as is, it clearly needs a rebasing (i think), as i wrote in the OP.

**Comment by mosabua** [comment]
Sure.. you can rebase and fix it up. But in general I like the content ..definitely an improvement and it fixes issue https://github.com/simpligility/android-maven-plugin/issues/495

**Comment by WonderCsabo** [comment]
Thanks for the feedback. I agree the content is good. :) But this unlock screen thing really annoys me.

**Comment by mosabua** [comment]
Maybe we can ensure via some sort of api call that it is unlocked before we start the tests. I vaguely remember we had something like that in the past.

**Comment by WonderCsabo** [comment]
I found [this](http://developer.android.com/tools/testing/activity_testing.html#UnlockDevice) method. However, this seems to be deprecated. Also in comments it is said that the current method is more reliable... Finally, this would add noise to the sample app. But we can try it anyway.

**Comment by mosabua** [comment]
We used to use this. 

https://github.com/simpligility/android-maven-plugin/blob/master/wait_for_emulator

**Comment by mosabua** [comment]
The unlock device thing seems horrible with code and manifest requirements. Surely there is some better way.. maybe a config on how to start up the emulator or something.

**Comment by WonderCsabo** [comment]
@mosabua that script is used to wait for the emulator to start, and block until. It has nothing to do with the lock screen. Actually this PR also [use](https://github.com/simpligility/android-maven-plugin/pull/641/files#diff-354f30a63fb0907d4ad57269548329e3R35) that (a modified version). The lock screen is dismissed with [this](https://github.com/simpligility/android-maven-plugin/pull/641/files#diff-354f30a63fb0907d4ad57269548329e3R36) command (which was completely missing before).

**Comment by WonderCsabo** [comment]
I asked this on [adt-dev](https://groups.google.com/forum/#!topic/adt-dev/19XXQ1kC15g), but i am being ignored. @mosabua please ask this directly if you can...

**Comment by malachid** [comment]
The script that Manfred was talking about was always an unreliable pain
because it was timing specific. It we turned on debug logging, it would
behave differently.

It sounds like you are trying to find something to unlock the lockscreen
once the emulator is running. Looking on Stack Exchange, it seems that the
different adb methods (like sending the menu key) are specific to certain
OS releases. What about programmatically sending a wake lock?

Alternatively, if we start up an emulator, configure it to never go to
sleep... Maybe we can take a snapshot and reuse it rather than starting a
new one?

**Comment by WonderCsabo** [comment]
> Maybe we can take a snapshot and reuse it rather than starting a new one?

That would mean saving the snapshot image into the repository, not something i would prefer.

> The script that Manfred was talking about was always an unreliable pain because it was timing specific. 

We still use that script (modified version), unfortunately there is no better solution. But that script is okay, at least it works reliably.

> What about programmatically sending a wake lock? 

I think i wake lock is not enough, you have to disable the lock screen also. I already linked [this](http://developer.android.com/tools/testing/activity_testing.html#UnlockDevice) method, hinted by the official Android doc, but it is deprecated and horrible.

**Comment by mosabua** [comment]
Can we maybe create a emulator image that has no lock screen functionality at all?

**Comment by WonderCsabo** [comment]
@mosabua i Googled for this for an hour (literally) and i did not found any remedy.

**Comment by mosabua** [comment]
It seems ridiculous .. is nobody using emulators in CI usage? Any hints on how to get around the lock screen for CI usage running integration tests  @JakeWharton @orrc @kingargyle @ducrohet

**Comment by WonderCsabo** [comment]
@mosabua maybe i am a noob, but this is very annoying indeed.

**Comment by JakeWharton** [comment]
Use adb to send keyevent 82. See:
https://github.com/JakeWharton/NotRxAndroid/blob/master/.travis.yml

**Comment by JakeWharton** [comment]
Can also have test runner unlock and wake up the device:
https://github.com/JakeWharton/u2020/blob/master/src/androidTestInternal/java/com/jakewharton/u2020/U2020TestRunner.java

**Comment by WonderCsabo** [comment]
@JakeWharton Thanks! We already [use](https://github.com/simpligility/android-maven-plugin/pull/641/files#diff-354f30a63fb0907d4ad57269548329e3R36) that, and it turned out sometimes that command does not unlock the emulator. At least the [screenshots](https://github.com/WonderCsabo/hello/blob/73.1/screenshots/emulator-5554_test_unknown_sdk_phone_armv7/0000.png) says that.

**Comment by WonderCsabo** [comment]
I try to second approach ASAP.

**Comment by mosabua** [comment]
Thanks @JakeWharton ... @WonderCsabo maybe it is working and the screenshots are just a timing issue. Maybe if we get it to pass consistently, even without screenshots, that would be good.

**Comment by WonderCsabo** [comment]
@mosabua the screenshots are fine i think. Actually our tests are failing, because Espresso is complaining about the unfocused window. The window is unfocused because the lock screen is on top and not our Activity.

**Comment by WonderCsabo** [comment]
[This](https://travis-ci.org/WonderCsabo/maven-android-plugin/builds/67328053#L3875) is the failure we get beause of the locked screen.

**Comment by malachid** [comment]
I saw others had the same problem a year ago on another project and
contributed a fix

https://github.com/finn-no/android_emulator_hacks



Malachi de Ælfweald
http://www.google.com/profiles/malachid

**Comment by WonderCsabo** [comment]
@mosabua it seems it fixed our problem, thanks to @JakeWharton. However, we had to add two permissions to the app manifest. I remember you did not like that. Are you okay with it? If not do you have an idea to not add this to the app manifest directly?

**Comment by mosabua** [comment]
Lets just add it and get this merged. For production usage I would not like that but you could always modify the manifest in a profile or whatever. Lets not worry about this though.

**Comment by WonderCsabo** [comment]
@mosabua let me clean up the commit history, then you can merge it.

**Comment by mosabua** [comment]
Sounds good. Alternatively I can merge it manually and squash it. Or you can create a new branch off it that does that and a new pull request ;-) 

If you want me to squash it just let me know the details for the commit summary...

**Comment by WonderCsabo** [comment]
I am rebasing this branch.

**Comment by mosabua** [comment]
Sounds good.

**Comment by mosabua** [comment]
Ping me when you are happy and want me to merge. Dont forget the changelog entry ;-)

**Comment by WonderCsabo** [comment]
Done, i hope you the change grouping is okay. Let's wait for the CI.

**Comment by WonderCsabo** [comment]
@mosabua i think this is finished.

**Comment by mosabua** [comment]
You rock @WonderCsabo ;-)

**Comment by mosabua** [comment]
Check it out @simpligility/android-maven-plugins-core-committers

**Comment by mosabua** [comment]
And now master builds and we are green ;-)

**Comment by malachid** [comment]
Sweet. Great job Csaba.

**Pull request merged**
