### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by WonderCsabo**
Implements #726 .

### CODE REVIEW

**Comment by mosabua** [comment]
Hmm. merging that did not do the trick. I cant look at this yet though...

**Comment by mosabua** [comment]
Just seems to have timed out..

**Comment by WonderCsabo** [comment]
Strange, it worked for me consistently. Please try to restart the build to
make master branch green.

**Comment by mosabua** [comment]
Green... beautiful green on master.

**Pull request merged**
