### PR TITLE
added x86_64 and mips64 architectures

### PR DESCRIPTION
**Pull request by kedzie**

### CODE REVIEW

**Comment by Shusshu** [comment]
@johanlindquist @malachid

**Comment by kedzie** [comment]
@johanlindquist  @malachid,  u see any issues with this?  I can add some test cases..

**Comment by malachid** [comment]
Sorry, missed the @mention. I think we should also include 'arm64-v8a' as well, right?

**Comment by kedzie** [comment]
Yeah I suppose so. U suggesting that I do it? I could.

**Comment by malachid** [comment]
If you are comfortable including it with this, yes. If not, please create a
ticket for it.

**Comment by kedzie** [comment]
On second thought I don't know what you're talking about..  I have ndk 10e and I'm not seeing a toolchain for that.. maybe you can educate me.

**Comment by malachid** [comment]
They are listed here

https://developer.android.com/ndk/guides/abis.html

They are also split out automatically if you use Gradle with the splitabi
function.

**Pull request merged**
