### PR TITLE
Junit4 test runner

### PR DESCRIPTION
**Pull request by secondsun**
Fixes https://github.com/simpligility/android-maven-plugin/issues/623 and supplies JUnit runner.

Also fixes https://github.com/simpligility/android-maven-plugin/issues/617 (see a9f051f)

### CODE REVIEW

**Comment by secondsun** [comment]
I need the Android support stuff to be installed in maven local for the test to work.  I've tried setting the m2 repository android creates in the sdk as part of my repositories in the test, but this doesn't seem to be working.  Suggestions?

**Comment by william-ferguson-au** [comment]
Have you tried creating a hosted repository in Nexus that points to the Android SDK m2 repo?

**Comment by secondsun** [comment]
I mean it runs on my machine and if I deploy with the sdk deployer I don't need the repository stuff in the test project's pom.  This is a no sdk deployer on Travis problem.

**Comment by mosabua** [comment]
I am inclined to remove the execution of the IT tests from the travis run to be honest. I has mostly been failing anyway.

In the long run we hopefully get the provision mojo implemented so that we can get the SDK Maven repos into the local Maven repo and then run IT's on travis again. 

Wdyt @simpligility/android-maven-plugins-core-committers

**Comment by mosabua** [comment]
Merged this now and also disabled the IT tests to see if this goes green in travis as it should..

**Pull request merged**
