### PR TITLE
Regex support for VersionGenerator

### LINKED ISSUE #605: More flexibility in versionCode generator
As the source code shows, currently the `versionCode` generator discards any character not a digit or period in version name. This would, for example, fail when faced with a `git describe`-formatted version name as generated by the `git-commit-id-plugin`. AFAIK this could not be solved without forking either plugin or changing the versioning scheme.

We can possibly allow configuration of version part separator characters, so that these use cases are covered.

### PR DESCRIPTION
**Pull request by xen0n**
This fixes #605, complete with test cases. Hopefully I didn't miss anything important (the XML part is automatically done by the mojo, right?); please review.

Thanks!

### CODE REVIEW

**Comment by william-ferguson-au** [comment]
Haven't had a chance to run it up but it looks good.
Double points for adding tests :-)

**Comment by william-ferguson-au** [comment]
Any other @simpligility/android-maven-plugins-core-committers want to chime in?

**Comment by Shusshu** [comment]
I also looked at it and I like it but currently I can't test this and at least the default behaviour looks like it will be triggered if you don't specify a pattern so it would be a low risk to merge.

**Comment by xen0n** [comment]
Any heads-up on this? Still I haven't found a way to completely implement the old behaviour with regexes. I'd rather not introduce flags or similar things, only for the sake of getting rid of old code...

**Comment by mosabua** [comment]
So wdyt @simpligility/android-maven-plugins-core-committers  .. pull this in and break old behaviour as part of a 4.2.0 release?

**Comment by william-ferguson-au** [comment]
Yep - merge it.

**Comment by Shusshu** [comment]
Merge this in :)
Btw it does not break old behaviour as it can still fallback to the old code...

**Pull request merged**
