### PR TITLE
Fix for the D8 compiler integration

### PR DESCRIPTION
**Pull request by cfiehe**
This commit fixes the D8 compiler integration. Because the D8 compiler options differ from those provided by the dex compiler, the `<dex>` tag cannot be used for D8 configuration. There is no way to set e.g. the minApi within the `<dex>` tag, because the DexMojo defines no corresponding parameter. This commit separates the two configurations and introduces a new `<d8>` tag for D8 compiler configuration.

If you want to use the D8 compiler, you can use the following plugin configuration in your pom:
```
<dexCompiler>d8</dexCompiler>
<d8>
    <minApi>26</minApi>
    ...
</d8>
```

Signed-off-by: Christoph Fiehe <christoph.fiehe@materna.de>

### CODE REVIEW

**Comment by mosabua** [comment]
From what I can tell this is an incompatible change right? So users are forced to update their pom if they adopt this potentially new release of the plugin.

**Comment by mosabua** [comment]
@william-ferguson-au what do you think... this seems a follow up to your PR https://github.com/simpligility/android-maven-plugin/pull/781/files

**Comment by cfiehe** [comment]
There are no changes necessary for all those users who migrate to a follow-up release containing this extension. If you do not specify the `dexCompiler`, `dex` gets used by default. The existing `dex` element is still valid, has the same configuration properties and refers to the same Mojo as before. The new `d8` element is just a replacement.

**Comment by william-ferguson-au** [comment]
Sorry @mosabua I'm too tired to reason this one through.

**Pull request merged**
