### PR TITLE
658 build config example

### PR DESCRIPTION
**Pull request by spyhunter99**

### CODE REVIEW

**Comment by mosabua** [comment]
Can you add an IT test that builds this apk and deploys it and maybe even does some verification?

**Comment by spyhunter99** [comment]
The only verification test possible is to check the generated class file, actually deploying it to android isn't necessary. I can look into it, but I don't have a huge amount of time to donate to this

**Comment by mosabua** [comment]
Just add a test that build the project then and forget about verification.

**Comment by spyhunter99** [comment]
ok i think i found where to add the tests. will push shortly

**Comment by spyhunter99** [comment]
I'm currently getting the following test failure. Doesn't look related to the test project I added. Is this a known issue?

Test set: com.simpligility.maven.plugins.android.AndroidSdkTest
-------------------------------------------------------------------------------
Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.181 sec <<< FAILURE! - in com.simpligility.maven.plugins.android.AndroidSdkTest
validPlatformsAndApiLevelsWithDiffBuildTools1(com.simpligility.maven.plugins.android.AndroidSdkTest)  Time elapsed: 0.124 sec  <<< ERROR!
com.simpligility.maven.plugins.android.InvalidSdkException: Invalid SDK: Build-tools 22 not found. Check your Android SDK to install the build tools 22
	at com.simpligility.maven.plugins.android.AndroidSdk.getBuildToolInfo(AndroidSdk.java:275)
	at com.simpligility.maven.plugins.android.AndroidSdk.getPathForBuildTool(AndroidSdk.java:260)
	at com.simpligility.maven.plugins.android.AndroidSdk.getAaptPath(AndroidSdk.java:168)
	at com.simpligility.maven.plugins.android.AndroidSdkTest.validPlatformsAndApiLevelsWithDiffBuildTools1(AndroidSdkTest.java:120)

**Comment by Shusshu** [comment]
I wrote that test.

It cannot find the build-tools 22 which is required for that test

**Comment by spyhunter99** [comment]
Well the tests are added. I also added a ignore flag for the one test that fails. I'm not sure what travis is complaining, but it doesn't look related to the changes

**Comment by WonderCsabo** [comment]
@spyhunter99 the [failure](https://travis-ci.org/simpligility/android-maven-plugin/builds/74564900#L3646) occurred exactly at your test class. Does this pass for you locally? If yes, you should add an echo statement in the Travis script to check out the maven log.

**Comment by spyhunter99** [comment]
Maybe i'm doing something wrong. I'm just running mvn clean install and it's building just fine here

**Pull request merged**
