### PR TITLE
Use ps -Af when needed to locate the right process

### PR DESCRIPTION
**Pull request by dukescript**
Debugging for Android not working. Currently (in [NB 10](https://netbeans.apache.org/download/nb100/nb100.html)) the debugging of Android applications isn't working through nb and Maven and needs to be manually configured.

### CODE REVIEW

**Comment by eppleton** [comment]
+1 
Would be great, if this was merged. We're using NetBeans & Maven for Android development, and currently debugging is very painful, as we manually need to attach the debugger (which also sometimes fails).

**Comment by mosabua** [comment]
fyi its gonna take me a bit to get it all into place but working on it.  
https://github.com/simpligility/android-maven-plugin/issues/786

**Comment by eppleton** [comment]
Thanks a lot for the update. BTW, you’re originally from Bavaria right?

 

Von: Manfred Moser <notifications@github.com> 
Gesendet: Sonntag, 10. März 2019 06:23
An: simpligility/android-maven-plugin <android-maven-plugin@noreply.github.com>
Cc: Anton Epple <toni.epple@eppleton.de>; Comment <comment@noreply.github.com>
Betreff: Re: [simpligility/android-maven-plugin] Use ps -Af when needed to locate the right process (#784)

 

fyi its gonna take me a bit to get it all into place but working on it.
#786 <https://github.com/simpligility/android-maven-plugin/issues/786>

**Comment by dukescript** [comment]
Any update on this? We have prepared everything for NB 11 to get Debugging to work again.

**Pull request merged**
