### PR TITLE
updated dependency versions from Android SDK to latest

### PR DESCRIPTION
**Pull request by mosabua**
This currently doesnt even build.. but we can use the branch to get this working together. feel free to chip in @simpligility/android-maven-plugins-core-committers .. might also help with the Jack support from @secondsun once we got it working and merged since there is a jack-api dependency available that we might be able to use.

### CODE REVIEW

**Comment by Shusshu** [comment]
This dependency is missing..... great job google!
 Could not find artifact com.android.tools.external.com-intellij:uast:jar:145.597.3 in central

Previous version is fine

**Comment by mosabua** [comment]
Maybe we should update to the previous version instead @Shusshu .. at least as a first step for merging. And in parallel pester the SDK team about the missing artifact.

**Comment by Shusshu** [comment]
Sure I had a try for 30min and reverted back finally ^^

Too many changes. I tried also to take just the version above the one we have but there also many changes, and each version has changes....

I think it's still better to first get them to fix their artifact as 2.2.0 was a major release. 
We wouldn't want to update with lots of changes twice


My findings:
In AndroidSdk:
SdkManager becomes AndroidTargetManager but I cannot resolve ProgressIndicator

In ManifestMergerMojo:
We can easily update the last method mergeManifests by also changing that object MavenManifestDependency


In AbstractAndroidMojo
VariantConfiguration.getManifestPackage( manifestFile )  is gonna be a pain to change to a non static method

**Comment by Shusshu** [comment]
See https://github.com/simpligility/android-maven-plugin/pull/757

**Pull request closed without merging**
