### PR TITLE
Automatically forward JDWP connection

### PR DESCRIPTION
**Pull request by jtulach**
For your consideration: I'd like to simplify debugging of Android applications when using the android-maven-plugin. I am attaching initial sketch that does the job for me. I am ready to polish it according to your suggestions.

Annoying thing on debugging (at least for me) is to find a PID number of just launched process and establish JDWP forwarding, so I can connect my debugger to it. I believe all of this can be automated.

My pull request allows one to specify port number via -Dandroid.run.debug=1234 and the plugin then takes care about the rest.

### CODE REVIEW

**Comment by Shusshu** [comment]
This would break backwards compatibility

Is there a default port used in most cases? (that could be set if the user uses the old way of android.run.debug=true)

**Comment by jtulach** [comment]
My intent was to keep backward compatibility. The value -Dandroid.run.debug=true is still recognized - in such case no port forwarding is done, as it was the case before my changes.

There is no default port. But what could be done is to find not yet used port and forward the jdwp connection to it - and print its value in the output - something like "Debugger is ready on 5432 port". I can do it if such idea seems useful.

**Comment by jtulach** [comment]
Anything else I can do to help this pull request be accepted?

**Comment by Shusshu** [comment]
For the moment (next several weeks or month) I'm not able to test anything.

I'd wait for another collaborator to check this out.

**Comment by mosabua** [comment]
I will try to get to it over the next week.

**Comment by jtulach** [comment]
Btw. I am trying to orchestrate this #584 pull request and a [necessary change in NetBeans IDE](https://netbeans.org/bugzilla/show_bug.cgi?id=250459) and make sure they work well together. Hopefully interested parties will be able to agree on both ends of the connection.

**Comment by mosabua** [comment]
I had to update the Run config class to use String as datatype as well so that pom based configuration works. Otherwise this seems to work okay. I updated docs and will add changelog in a sec as well.

**Pull request merged**
