### PR TITLE
Fix buildConfigConstants parameter

### LINKED ISSUE #722: Strange buildConfigConstants parameter
I just found the [`buildConfigConstants`](https://github.com/simpligility/android-maven-plugin/blob/74044942cc35f4e60f80f8d8c42a1c4ec4698363/src/test/projects/buildConfigInjection/pom.xml#L79) parameter, which is very strange to me:

1. Why plural form in the inner elements? I guess it is only the problem of the example.
2. IntelliJ marks the `buildConfigConstants` section in red, like it is missing from the plugin declaration.
3. It is not in the [generated doc](http://simpligility.github.io/android-maven-plugin/generate-sources-mojo.html), either.

Maybe because it is [`read-only`](https://github.com/simpligility/android-maven-plugin/blob/74044942cc35f4e60f80f8d8c42a1c4ec4698363/src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java#L227)? Why is that? @mosabua some hints?

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes #722.

### CODE REVIEW

**Comment by william-ferguson-au** [comment]
How was the test (NB not an example) passing?

**Comment by WonderCsabo** [comment]
@william-ferguson-au sorry i am not sure what you mean. I ran `mvn install`, and everything passed.

BTW, the CI should be fixed. :)

**Comment by william-ferguson-au** [comment]
This file https://github.com/simpligility/android-maven-plugin/pull/723/commits/7882632b3fbf635a48332ed501629ac6d7605922#diff-48446e85d4a0808f1f3e2975d47c60b5 is a **test** POM.** It is not an example.**

I want to know why the tests didn't fail BEFORE you made the change.
Is that test POM never used?
Do the tests not check the output in BuildConfig?
Do the tests not check the correct thing?

**Comment by WonderCsabo** [comment]
Sorry for the confusion. I will rephrase my second commit message.

Apparently, Maven accepted the inner element names that way, so it was still working before!

**Comment by mosabua** [comment]
Maven collections only work on the outter tag. The inner tag just has to be valid. The tag name is arbitrary. So in this example it could have been

<buildConfigConstants>
  <foo>
    <name>Title</name>
    <value>${project.name}</value>
    <type>String</type>
  </foo>

I am still okay with the merge though so thanks..  we need to probably update the changelog..

**Comment by william-ferguson-au** [comment]
Changelog already updated.

**Pull request merged**
