### PR TITLE
#655 Maven site command fails with test projects

### PR DESCRIPTION
**Pull request by spyhunter99**
] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project libraryprojects-parent: failed to get report for org.apache.maven.plugins:maven-javadoc-plugin: Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources (default-generate-sources) on project libraryprojects-tests: Execution default-generate-sources of goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources failed: String index out of range: -1 -> [Help 1]

### CODE REVIEW

**Comment by mosabua** [comment]
So you are saying if we merge this in, we get the failure on this project if we run mvn site?

**Comment by mosabua** [comment]
If so... want to submit a fix for it as part of this pull request and also add an integration test that runs the site (or modify the existing one to include site)

**Comment by spyhunter99** [comment]
If merged in, "mvn site" will fail. Everything else works as normal. I'm not entirely sure what the root cause is

**Comment by mosabua** [comment]
Okay ... I will look at this when I have some more time in August unless someone else wants to jump in. I will leave it unmerged for now.

**Pull request merged**
