### PR TITLE
added testFailSafe option

### PR DESCRIPTION
**Pull request by kedzie**
so postIntegrationTest phase executes even if the tests failed.

### CODE REVIEW

**Comment by kedzie** [comment]
@mosabua any interest in this?  I think it is pretty valuable...

**Comment by kedzie** [comment]
@psorobka any interest in this?  I think it is valuable...

**Comment by kedzie** [comment]
@mosabua @psorobka  anyone out there? I think it makes sense to execute postIntegration phase even if tests fail, for cleanup tasks....

**Comment by mosabua** [comment]
HI @kedzie  ... I am extremely busy but I am trying to get all changes merged and a new release out asap. I am hoping before xmas..

**Comment by mpkorstanje** [comment]
@kedzie what is the reason for setting the default value of  `testFailSafe` to to true?

This makes broken builds pass which is contrary to the expectations  of a maven plugin.

**Pull request merged**
